### ISSUE TITLE
Determinación de campo detalle.tipoProducto de infile basado en campo de articulo

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#1]
El campo que solicita Infile en su web service, para definir si el producto es **Bien** o **Servicio**, debe unicamente llevar las letras **B** = Bien  o **S** = Servicio.

Configurar la aplicación para que determine esto basado en el campo de ERPNext del DocType **Articulo (Item)**, llamado **"Mantener Stock"** = **is_stock_item**

Comportamiento esperado:
Si el campo is_stock_item  esta seleccionado, entonces es Bien = B
Si el campo is_stock_item no está seleccionado, entonces es Servicio = S

**Comment by monroy95** [comment]
**Solucion:** Accede a cada uno de los artículos dependiendo de su código y verifica su valor por individual para luego asignar a tipoProductoTag_Value un Valor B o S

```
detalle_stock = frappe.db.get_values('Item', filters = {'item_code': codigoProductoTag_Value},	fieldname = ['is_stock_item'])
				if (int((detalle_stock[0][0])) == 0):
    					tipoProductoTag_Value = 'S'
				if (int((detalle_stock[0][0])) == 1):
					tipoProductoTag_Value = 'B'
```
