### ISSUE TITLE
Tipos de Documentos:  Factura Cambiaria

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#112]
- [x] 1. Agregar un campo que indique TURE/False si es factura cambiaria

- [ ] 2. El formato de impresión de factura cambiaria debe llevar cierto texto,indicado por el usuario, y un area de firma por parte del comprador.

**Comment by monroy95** [comment]
Para la peticion 2, personalizar los formatos de impresion
