### ISSUE TITLE
Pendiente configurar IDP y otros impuestos en FEL

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#114]

**Comment by monroy95** [comment]
Actualmente según docs, es necesario mostrar estos impuestos:

1. Petroleo
2. Turismo Hospedaje
3. Timbre de prensa
4. Bomberos
5. Tasa Municipal

**Comment by monroy95** [comment]
Hacer escenarios (excel, erp, jupyterlab...) en que se aplican estos impuestos :D

**Comment by monroy95** [comment]
Por ahora solo se ha agregado el impuesto para combustibles, se ira agregando según las necesidades de los usuarios
