### ISSUE TITLE
[Priority 10] - Batch Generation of Electronic Invoice

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#115]
- [x] 1. Create a multiple instance doctype, where user can select several invoices on a child table.  Those invoices will be members of the batch.

- [x] 2. Add button to apply validation (Submit) to sales invoices present in child table

- [x] 3. Add button to apply generation of electronic invoice signatures to sales invoices present in child table.

- [x] 4. Add functionality to Sales invoice Actions button to allow the batch validation and batch generation from there  (still the multiple instance doctype must be generated because of logs)

- [x] 5. Each batch generation must carry a log section readable by user, showing messages from INFILE.

**Comment by Tropicalrambler** [comment]
Pending review of functionality

**Comment by monroy95** [comment]
Generacion de log en commit: 49a78c366b21f018149f86bf7845720ef2340b89
