### ISSUE TITLE
Cancellation for FEL Invoice equate with ERPNext sales invoice cancellation

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#119]
Ability to cancel invoice with one click.
Cancelled but submitted  ( cannot erase it, but it doesn't play in accounting)

**Comment by Tropicalrambler** [comment]
At the moment of cancellation, a script must be run that reverts all the changes we made in 19 DocTypes.
19

**Comment by monroy95** [comment]
Usar esquema ANULACION.xml

**Comment by monroy95** [comment]
Se agrego un botón con un dialog para que el usuario indique el motivo de la anulación, aparece solo si la factura esta cancelada y que anteriormente haya sido generada como electrónica,

**Comment by monroy95** [comment]
El resto de registros quedan igual con misma serie y UUID con la diferencia que tras la anulación la factura PDF tiene una marca de agua como ANULADA
