### ISSUE TITLE
If no pincode (zip code) furnished AUTO-SELECT 01001

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#121]
Add auto selection of postal code "01001"  when absent.

Future:  if "ZONA ##"  Is included,  autoselect a zip code

**Comment by monroy95** [comment]
Se usaran valores default, en el caso que no exista una dirección o falte valor en campo de dirección: 

79611c1a5e24aed0d50b7d70d10f42a39ad4b1f4
