### ISSUE TITLE
Doctype: Rango de Retención Impuesto  (Tax Witholding Ranges)

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#124]
- [x] Child Table!

- [x] Data:  "Titulo"  name:  Title

- [x] Select:  "IVA" o "ISR"  name  "Tipo de impuesto"
- [x] Float: "Tasa"    Description:  "Tasa porcentual  p. ej  5.00  = 5%"

**Comment by Tropicalrambler** [comment]
Este child table se insertara en una sección de company  para poder asignarle esos rangos de retención.

**Comment by monroy95** [comment]
Child table agregada en:  e63cef779478b22dd7c4bd2535ac9a89226df359

**Comment by Tropicalrambler** [comment]
Perfect. Issue closed.
