### ISSUE TITLE
Integrar campo de IVA total al envio de Factura Electronica

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#14]
Este campo ya se calcula correctamente con el commit 71a4b037fcce036a286f0b2950ad759acbb40fb5.

Solamente falta integrarse a la data que se envia a Infile.

**Comment by monroy95** [comment]
Dato integrado en el envío a INFILE con el commit cfaa6af

**Comment by Tropicalrambler** [comment]
OK!

**Comment by Tropicalrambler** [comment]
Cerrando.
