### ISSUE TITLE
Special Invoice payment creation functionality

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#175]
Similar to retention payments with journal entry, this menu item will create a special invoice payment for Journal entry.
This Journal Entry will be created with three lines:
1. Retention amount for Income Tax (the standard %5 if <= 30K and  7% for anything above.)
2. VAT Tax amount "reversion"  (not a retention)  this is the VAT tax amount of the invoice, but instead of going to the VAT Receivable account as the invoice registered, it goes to the VAT Payable account to reverse the amount, so that it is "absorbed" by the company.
3. Cash difference from the grand total.

**Comment by monroy95** [comment]
Esto se incluyo con la generacion de factura especial electronica
