### ISSUE TITLE
Special Invoice Functionality

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#183]
Low Priority
- [ ] Future Functionality
User declares special invoice series in Naming Series definition, for purchase invoice.
In facelec configuration user specifies special invoice erpnext series as special invoice series.
When user selects the series for special invoice a Javascript will set the custom field we are creating as true.
Otherwise, user can specify manually upon creation of special invoice.
IMPORTANT:  This check field will be necessary for when generating monthly tax declaration for filtering which special invoices are included.

**Comment by monroy95** [comment]
It was decided to base on the invoice series to generate a special invoice or not, all of this can be configured in the Electronic Invoice Configuration, Purchase Invoices section.
