### ISSUE TITLE
Managing special characters with UTF-8 Systemwide

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#187]
UTF-8 Encoding MUST BE FORCED on all request headers and body, when receiving party does not require it.

Sourced from a generation error traceback where:
`UnicodeEncodeError: 'latin-1' codec can't encode character '\u202d' in position 3616: Body ('\u202d') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.`

Solution proposed by @monroy95 👍 
https://github.com/psf/requests/issues/4133

Append this to your xml data variable:

`.encode('utf-8')`

Make sure your headers variable has this.

`headers = {'Content-Type': 'text/xml; charset=utf-8'}`

**Comment by monroy95** [comment]
En la nueva modalidad FEL por default se manda enconding UTF8
