### ISSUE TITLE
Boton de generar factura en Sales Invoice y estatus del Sales Invoice

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#2]
El boton de generar factura electronica, debería salir sobre factura validada, independiente del estatus si esta pagada con anticipacion o no

**Comment by monroy95** [comment]
El script verifica si hay **cae** generado en relación a la serie de la factura. En caso no exista un cae se mostrará el boton de lo contrario se ocultara.

[https://github.com/sihaysistema/factura_electronica_gt/blob/master/factura_electronica/public/js/facelec.min.js](url)
