### ISSUE TITLE
Trade Name Custom Field for Customer and Supplier Doctypes

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#200]
Our application uses the field "customer_name"  as the official / legal field for invoice purposes.
customer_name:   The Official company name used for legal and fiscal purposes.  example: "Apple Inc". "Distribuidora Gigante de Herramientas S.A."

We want to have an additional custom field for the trade name:
trade_name: The business name without extras (no LLC, Inc. S.A., etc.)  Example: "Apple", "Mega Herramientas"

Custom Field:  Title "Trade Name". Name: "trade_name"  Description: "Name used for advertising or trade purposes.  For Example: Apple, Amazon or Home Depot"
Translation: Source: "Trade Name"  Target: "Nombre Comercial o Ficticio"

https://www.thebalancesmb.com/business-name-registration-397559

**Comment by monroy95** [comment]
NOTE: También se agrego al doctype company para usar en Generación Factura Electrónica

**Comment by Tropicalrambler** [comment]
Thanks!

**Comment by Tropicalrambler** [comment]
- [x] Add description to Custom field in Customer
- [x] Add description to Custom field in Supplier
- [x] Translation: Source: "Name used for advertising or trade purposes. For Example: Apple, Amazon or Home Depot" Target: "Nombre utilizado para publicidad o venta. Por Ejemplo: Apple, Amazon, o Home Depot"

**Comment by Tropicalrambler** [comment]
For clarification purposes:
### Legal Name: For government, tax, and other business use, usually contains endings such as S.A., LLC, Inc.  (Para uso con el gobierno y facturación, o con otros negocios para contratos, este contiene terminaciones como S.A., LLC, Inc.)
### Trade Name: A name used for conducting business, advertising and sales purposes, AKA "Fictitious Name" (Para uso en curso diario, publicidad, rotulos, tarjetas, etc. Must not include terms like S.A., Inc., LLC  También se le conoce como **Nombre Ficticio**. No debe incluir términos como S.A., Inc. LLC)

Doctype **Company**, field: **company_name**  = Legal Name, o "Razón Social o Nombre Registrado"

Doctype **Company**, Custom Field: **facelec_trade_name** = Trade Name o "Nombre Comercial o de publicidad de la empresa"

**Comment by Tropicalrambler** [comment]
Using JavaScript set properties, set description of fields
- [x] Add description to Doctype: Customer Field: **customer_name**:  "Legal Name, for tax, government or contract use. For Example: Apple, Inc. Amazon.com, Inc., The Home Depot, Inc."
- [x] Add description to Doctype: Supplier Field: **supplier_name**: "Legal Name, for tax, government or contract use. For Example: Apple, Inc. Amazon.com, Inc., The Home Depot, Inc."
- [x] Translation: Source: "Legal Name, for tax, government or contract use. For Example: Apple, Inc. Amazon.com, Inc., The Home Depot, Inc." Target: "Razón Social o Nombre Registrado, para uso de gobierno, facturacion, impuestos, o contratos. Por Ejemplo: Apple, Inc. Amazon.com, Inc., The Home Depot, Inc."
