### ISSUE TITLE
update wiki

### ISSUE THREAD

**Issue by jorux** [sihaysistema/factura_electronica_gt#219]
hi, sorry, im not familiar with github yet. 
i tried installing your app and saw that the point 4.6 on the wiki is oudated, since the application installer is deprecated. however, the command "bench --site 'site1.local' install-app factura_electronica" properly replaces this step

**Comment by monroy95** [comment]
The wiki has been updated, you can see the correct steps here: 
https://sihaysistema.com/wiki/factura-electronica/install
