### ISSUE TITLE
Migrate model of Item Type selector for Item from Gas, Good or Service to SAT provided taxable categories

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#228]
SAT Provides now a series of Taxable categories for individual items, named "Nombre Unidad Gravable"

This issue seeks to migrate the old model, to the new model, so that the three / 4 fields are deprecated, but supported in legacy installations. (migrated)

Users of the legacy system must be informed of the changes so that when updating they are aware of the actions necessary for proper functionality of the application.

See sample below:
<img width="944" alt="Screen Shot 2021-03-15 at 10 50 15 AM" src="https://user-images.githubusercontent.com/16600935/111189959-3b2a5100-857c-11eb-9e8c-6a6157efe437.png">

**Comment by monroy95** [comment]
Se oculto el check es exento ya que no estaba siendo utilizado (feature que ya no se completo) y así evitar confusión al usuario.

Se agrego nuevo comportamiento a los checks:
- Cada vez que se selecciona Bien/Servicio se ocultan los campos relacionados con los impuestos para combustibles para evitar confusión al usuario.
- Se agregaron mas descripciones y ejemplos al campo Nombre Unidad Gravable

![preview](https://user-images.githubusercontent.com/26640728/129785765-f4cc87ac-711b-42cc-9f90-39b7ef71a4dd.gif)
