### ISSUE TITLE
Sales Invoice validation rounded amount two two decimals

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#239]
Our validation field calculates quantity changes in the delivery note to ensure a strict 2 decimal placement of the amount. This should also copy to the sales invoice, such that when sending to SAT, it should also show the amount as 2 decimals.  

Verify.

**Comment by Tropicalrambler** [comment]
Customer wants to apply payments on two or three decimal places on the software without any additional decimals.

**Comment by monroy95** [comment]
El número de decimales a usar puede ser modificado en  `System Settings` en el campo `currency precision`

![image](https://user-images.githubusercontent.com/26640728/138926455-dd6f1f91-6f0c-4862-b82c-97c27fb297ce.png)


- [ ] Confirmar si esta es la funcionalidad que necesitan
