### ISSUE TITLE
Error al actualizar 'bench update --reset'

### ISSUE THREAD

**Issue by Expressgt** [sihaysistema/factura_electronica_gt#256]
Cuando se actualiza el modulo de factura electronica en conjunto con el sistema completo muestra un warning indicando "syntaxwarning", esto es un problema?
![warningFEL](https://user-images.githubusercontent.com/12967533/146381281-f47a5f67-04d5-43c2-80a1-d2b91d993e57.png)

**Comment by monroy95** [comment]
@Expressgt gracias por repórtalo, en si no es un problema solo es una validación ambigua para el compilador del interprete, se corrigió para que no vuelva a aparecer.
