### ISSUE TITLE
Campo cae_factura_electronica no encontrado.

### ISSUE THREAD

**Issue by Expressgt** [sihaysistema/factura_electronica_gt#258]
Al momento de instalar en ambiente limpio FEL (7.1.6) e intentar generar una primera factura indica el error "Campo cae_factura_electronica no encontrado.", anteriormente con la version 7.1.5 no indicaba dicho error.  Que ajuste se deberia hacer?
![image](https://user-images.githubusercontent.com/12967533/146660718-987bc6bb-367c-439b-b7d9-92fa632febac.png)

**Comment by Julio0250** [comment]
Adicional, tratando de configurar la empresa existe otro error. Creo que viene relacionado a lo mismo.

![image](https://user-images.githubusercontent.com/9574414/146709219-a9b764f6-f5c9-489a-a221-e49fb1e1cf0e.png)

**Comment by monroy95** [comment]
> Al momento de instalar en ambiente limpio FEL (7.1.6) e intentar generar una primera factura indica el error "Campo cae_factura_electronica no encontrado.", anteriormente con la version 7.1.5 no indicaba dicho error. Que ajuste se deberia hacer? ![image](https://user-images.githubusercontent.com/12967533/146660718-987bc6bb-367c-439b-b7d9-92fa632febac.png)

Gracias por reportarlo, el problema esta en el core Frappe que al ejecutar `bench migrate` no se migran los `custom field`  de facelec a la base de datos. En los próximos días saldrá un nuevo release de frappe con la solución.

https://github.com/frappe/frappe/pull/15288

**Comment by monroy95** [comment]
> Adicional, tratando de configurar la empresa existe otro error. Creo que viene relacionado a lo mismo.
> 
> ![image](https://user-images.githubusercontent.com/9574414/146709219-a9b764f6-f5c9-489a-a221-e49fb1e1cf0e.png)

Ese es un error de Frappe JS, no ha dado problemas con el funcionamiento

**Comment by monroy95** [comment]
https://github.com/frappe/frappe/releases/tag/v13.17.0
