### ISSUE TITLE
Mejora potencial

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#3]
Cuando una factura validada ya haya obtenido su factura electronica, si el usuario vuelve a cargar una factura en estado validado (pagada o impagada) entonces, que el botón ya no aparezca.

**Comment by monroy95** [comment]
El script verifica si hay **cae** generado en relación a la serie de la factura. En caso no exista un cae se mostrará el boton de lo contrario se ocultara.

El script se encuentra en la carpeta public.
