### ISSUE TITLE
NIT Validar desde servidor

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#34]
Actualmente el validador de nit funciona unicamente en ficha de cliente o proveedor, pero no lo hace cuando se abre un dialogo.  Mientras se resuelve eso generamos un script python validador del NIT, para asegurarnos que el NIT sea el correcto al  momento de enviar SOAP request.

**Comment by monroy95** [comment]
ISSUE resuelto en el commit 9d4d141 
Se agregó la validación de NIT en `Sales Invoice` con JS del lado del cliente, para agilizar la corrección del NIT por parte del usuario. Para futuras modificaciones se puede adaptar a cualquier DT.

**Comment by Tropicalrambler** [comment]
Listo!  MIL GRACIAS!
