### ISSUE TITLE
Nombre de documentos en "Configuracion Series" igual a campo 'serie'

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#37]
El nombre de cada record en la tabla secundaria o Child Table, cambiarlo a que sea igual a la data que se coloca en el campo `serie`, esto con el objetivo de permitir una búsqueda mas intuitiva de los datos que posee cada récord de configuración.

El ejemplo más tangible, es a la hora de desear obtener la data como el número de resolución, etc. en un formato de impresión Jinja, se utiliza esta forma de obtener los campos de ese record:

`{% frappe.get_doc('[DocType]','[nombre]') %}`

Como es usual, uno desea obtener esta data en referencia de una serie elegida por el usuario al momento de facturar.  Como cada serie podrá ser miembro de una configuracion distinta, proveedor de servicios de facturación distinto, distintas resoluciones, etc., la serie puede ser utilizada para retroactivamente obtener la información relacionada a ella.

Un ejemplo para **Sales Invoice** es que cuando el usuario configure el formato de impresión desde la plantilla de impresión con Jinja, tenga accesible estas variables, y pueda obtener automáticamente con el valor del campo `naming_series` de la Factura de Venta, los campos que estén asociados a esta, basado en nuestra aplicación.

Con esto nos aseguramos simplicidad de configuración al instante, conforme se va usando el programa.

**Comment by Tropicalrambler** [comment]
Non sequitur. No es necesario.  Lo que si podemos hacer es almacenar en un campo de facelec_resolucion en la factura, para que quede fijo y se pueda usar en Jinja a la hora de imprimir.

La solucion implica:

- [ ] Crear un nuevo campo en Factura  llamado  facelec_resolucion.  Es read only.  Se obtiene el valor de la resolucion, basado en la serie elegida por el usuario. Se actualiza cuando cambie de serie.

- [ ]

**Comment by monroy95** [comment]
**Funcionamiento:**

![numero-resolucion](https://user-images.githubusercontent.com/26640728/43560146-5d018776-95ce-11e8-8da7-e86687da10b7.gif)

**Comment by monroy95** [comment]
**Funcionamiento:**

![numero-resolucion](https://user-images.githubusercontent.com/26640728/43560304-07e66c92-95cf-11e8-985a-003de6739566.gif)

**Comment by monroy95** [comment]
Esto aplicaba para GFACE, si es necesario reabrir issue
