### ISSUE TITLE
No muestra total de servicios

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#46]
Cuando hay servicios listados en la factura, no se muestra el total del calculo, contrario a artículos o combustibles.

Debería mostrarlo.

**Comment by monroy95** [comment]
Revision de código para funcionamiento correcto edabb5750fb42c420abc8e98e1c360208d4cc811

**Comment by Tropicalrambler** [comment]
OK.  Este funciona.
