### ISSUE TITLE
Javascript validador de Fiscal Tax Category

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#51]
El campo de Tax per category
[ ] Renombrarlo:  Fiscal Tax Category
[ ] Agregarle descripcion: Choose only one.

[ ] Establecer validador para que solo pueda elegirse uno.
Este validador, no mostrará mensaje sino que al usuario cambiar a otra categoría, automáticamente quita el cheque, al estilo botones de radio HTML.

Este estilo precisamente:
https://www.w3schools.com/html/tryit.asp?filename=tryhtml_radio

**Comment by monroy95** [comment]
Se agregó el validador en el commit a9cde4eda7cd0a386728f839bda3632dd3c2f068

**Comment by Tropicalrambler** [comment]
Esta ya estaba desde la semana anterior a la que se cierra el issue.
