### ISSUE TITLE
Quitar botón de Activar o Desactivar y que se pueda Validar la configuracion

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#53]
Si se valida, esta activa, si no se valida, no esta activa.  Si se cancela la activa, se puede duplicar o reactivar. Asi seguimos también el rastro de cambios en las configuraciones!

**Comment by monroy95** [comment]
Esta funcionalidad permite cancelar, corregir, validar configuraciones para factura electronica, se desactivo la funcionalidad de borrar configuraciones para llevar el registro de intento de modificaciones. Tomar en cuenta que solo se permite tener una configuración validada y esta se tomara para la generación de factura electronica.

![captura de pantalla 2018-05-13 a la s 19 27 47](https://user-images.githubusercontent.com/26640728/39974130-c88fce64-56e3-11e8-929d-f0a5b06acedb.png)

**Comment by Tropicalrambler** [comment]
Mejor solucion que la que yo propuse. Bien hecho!
