### ISSUE TITLE
Habilitar Factura Especial

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#55]
1. Agregar sección en configuración de Factura Electrónica para que se pueda asignar la factura especial a series de Factura de Compra
2. Agregar la funcionalidad a Facturas de Compra para poder enviar la factura especial.

**Comment by Tropicalrambler** [comment]
**Comportamiento Actual**
Se puede realizar una factura de compra, y dependiendo del valor del servicio,
agregar o restar IVA.

**Comportamiento Esperado**

Al cargar el precio del Item, se estimará el valor incrementado por EL ISR  con una division por .95
A este resultado, se le calcula el IVA, y tambien se le calcula el ISR.  

Ejemplo:
Del total de una factura de 4,715.79, yo puedo derivar la base de la siguiente forma:
1. Base + ISR por pagar + IVA por pagar
2. Base + ((Base/0.95)*Tasa ISR) + ((Base/0.95)*Tasa-IVA)
3. Base + ((Base/(1-Tasa ISR))*Tasa ISR + ((Base/(1-Tasa ISR))*Tasa IVA  = Grand Total (de la linea!)

Base
Tasa ISR -  Ingresarla en Configuración
Tasa IVA - Tabla de Impuestos

OJO: Separar cuentas contables de IVA credito fiscal Tabla impuestos
IVA: IVA por cobrar (esto es un credito para nosotros)
IVA: IVA por Pagar (tambien se genera!)
ISR: ISR Por pagar (si se genera un pasivo, el cual despues se anula con un pago de ISR al Fisco)

**Comment by amorenodlc** [comment]
[Factura Especial.pdf](https://github.com/sihaysistema/factura_electronica_gt/files/3224855/Factura.Especial.pdf)

**Comment by Tropicalrambler** [comment]
https://portal.sat.gob.gt/portal/descarga/1740/factura-electronica/5062/factura_especial_electronica.pdf

**Comment by amorenodlc** [comment]
Factura por compra de combustible; Hay diferencia en Total GT Q.15.00 vrs en palabras GT. quince y un solo centavo. Favor a la brevedad de corregir este problema. Adjunto el pantallazo.

**Comment by monroy95** [comment]
Verificar metodo de crear un **Purchase Taxes and Charges Template** con las cuentas especificas
