### ISSUE TITLE
Al convertir de Orden de venta a Factura, no jala el codigo 3 digitos unitario

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#60]
Revisar porque?

**Comment by monroy95** [comment]
Verificar código:
**ERPNext**
https://github.com/frappe/erpnext/blob/fc2292f08cc16373f11c978f6ca8b11220c9fef1/erpnext/selling/doctype/sales_order/sales_order.py#L541

https://github.com/frappe/erpnext/blob/fc2292f08cc16373f11c978f6ca8b11220c9fef1/erpnext/selling/doctype/sales_order/sales_order.js#L362

**Frappe**
https://github.com/frappe/frappe/blob/0363a64c21b7fcce50f6073196aa891ae0d466d1/frappe/public/js/frappe/model/create_new.js#L286

**Comment by Tropicalrambler** [comment]
Queda pendiente revisar como hacer para incluir los custom fields en una duplicación o creación de otro doctype a base de un doctype:  Ej  sales order -> Sales invoice

**Comment by monroy95** [comment]
Lo que puede influir en que no se copie el código de 3 dígitos, es porque todos los campos customizados tiene diferentes nombres. 

Mientras se resuelve por favor volver a cargar cada item

**Comment by Tropicalrambler** [comment]
Listo. 😀
