### ISSUE TITLE
Campo de CAE no se debe copiar cuando se Duplica una factura electronica

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#61]
El CAE se esta copiando de una Factura en ERPNext a otra, esto no debe de ser asi.

**Comment by monroy95** [comment]
d45ce7fc88a223b9cd328f47abf946d0ba00799c cuando se duplique una factura limpiara los campos: **`cae_factura_electronica`** y **`serie_original_del_documento`** evitando así copiar los datos
