### ISSUE TITLE
Conversion de unidades

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#64]
Cuando se cambia el factor de conversion, solo hasta que se hace CLICK fuera del campo, se calcula correctamente... es el listener de ese campo al hacer blur?

**Comment by monroy95** [comment]
Se realizaron optimizaciones en [facelec-v11](https://github.com/sihaysistema/factura_electronica_gt/tree/facelec-v11).

- [ ] **Confirmar Funcionamiento**

**Comment by Tropicalrambler** [comment]
No se esta calculando automaticamente. Somos nosotros?

**Comment by monroy95** [comment]
Se agregaron listener a los campos, y una realizacion extra de los calculos al momento de guardar
