### ISSUE TITLE
Tabla de Tax breakup

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#67]
Agregar una tabla nueva donde se especifique con claridad como se hizo el calculo de IDP. La tabla inferior, debe llevar el calculo de IVA.  Estilizarla correctamente y mostrarla usando el codigo special_tax.py que cambia los valores de los impuestos.

**Comment by Tropicalrambler** [comment]
Esto consistirá en una CONFIRMACION visual (mientras se logra ajustar el controlador de impuestos) de que si se llevaron a cabo los cambios en contabilidad.

**Comment by monroy95** [comment]
Disponible en la actualización para v11, aplicada en Sales Invoice, Purchase Invoice

<img width="895" alt="Captura de Pantalla 2019-05-28 a la(s) 18 01 27" src="https://user-images.githubusercontent.com/26640728/58519908-a837e100-8172-11e9-9fe4-17e8c6c93b11.png">

**Comment by Tropicalrambler** [comment]
Listo. 😀
