### ISSUE TITLE
Bug: Campos de dialogo de sales invoice item no despliegan los colapsibles. Puede ser nuestros triggers.

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#68]
Revisar los triggers y limpiar código fuente para asegurarse que funcione adecuada.

**Comment by monroy95** [comment]
Solución en la rama [facelec-v11](https://github.com/sihaysistema/factura_electronica_gt/tree/facelec-v11)

**Comment by Tropicalrambler** [comment]
Gracias!
