### ISSUE TITLE
Agregar en configuracion para guardar automaticamente PDF en servidor local

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#7]
Agreguemos una configuracion que le permita al cliente elegir, si guarda o no el PDF en el servidor.   En caso de si elegirlo, obtener el pdf desde el servidor de INFILE al momento de la creación, y guardarlo en la carpeta de archivos privados.  Y adjuntarlo

Indicarle al usuario que de elegir esto, se consumirán recursos de su servidor, pero podrá independizar sus pdf's de INFILE.

Los archivos se guardan en /private/facturas_electronicas/[AÑO]/[MES]/nombre-archivo.pdf

**Comment by monroy95** [comment]
Nota: Realizar esto requiere crear un script que realice la descarga del archivo y lo ubique en el directorio deseado

**Comment by monroy95** [comment]
Archivo adjunto de factura.

![captura de pantalla 2018-07-05 a la s 13 27 42](https://user-images.githubusercontent.com/26640728/42343770-5703cfd2-8057-11e8-8127-a3ee5ec3c277.png)

**Comment by Tropicalrambler** [comment]
Calidad!
