### ISSUE TITLE
Implementacion paraMexico

### ISSUE THREAD

**Issue by raul-sanz** [sihaysistema/factura_electronica_gt#73]
Podria usarla para generar facturas de mexico o solo es para guatemala

**Comment by Tropicalrambler** [comment]
No te se responder de inmediato, sin embargo, podemos platicar vía Gitter para aclarar tus dudas y ver si se puede desarrollar algo para México.  Tienes dos caminos:
1. Nos das especificaciones y la desarrollamos para ti
2. Utilizas nuestro código fuente para adaptarlo a las necesidades de los proveedores de Factura Electrónica en México (si es que es permitido por tu [Autoridad Fiscal] (https://www.sat.gob.mx/personas/factura-electronica))
