### ISSUE TITLE
Revisar triggers de campo de proveedor, no se puede ingresar nombre con teclado

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#81]
Es imposible ingresar el nombre del proveedor en un recibo de compra manualmente, hay que elegirlo de un drop-down.

**Comment by Tropicalrambler** [comment]
Esto es probablemente por los disparadores de cálculos JavaScript, revisar funcionalidad para simplificarlo.

**Comment by monroy95** [comment]
Se comentaron las siguientes lineas de código:

<img width="739" alt="captura de pantalla 2019-01-14 a la s 15 11 31" src="https://user-images.githubusercontent.com/26640728/51141392-bcf08980-180e-11e9-80e1-064507fff9f8.png">

**Comment by monroy95** [comment]
Solucionado en la rama [facelec-v11](https://github.com/sihaysistema/factura_electronica_gt/tree/facelec-v11)

**Comment by Tropicalrambler** [comment]
Muchas gracias!
