### ISSUE TITLE
Error en suma de Profit & Loss Statement

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#86]
Al momento de duplicar facturas de venta, no se elimina una fila de nuestros cálculos de IDP para cuentas, por lo tanto genera error en los montos indicados en el profit & loss.  Revisar toda la lógica para asegurar precisión irrespectivo de forma de creación de nueva factura.

**Comment by monroy95** [comment]
Se optimizo JS en la rama facelec-v11.

- [ ] Confirmar funcionamiento

**Comment by monroy95** [comment]
Cambio se aplico para version-12, reabrir issue si falla vuelve a presentarse
