### ISSUE TITLE
Unable to Submit Purchase Invoice with Stock Entry checked

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#89]
The error shown is this:
**Debit and Credit not equal for Sales Invoice #. Difference is**

Based on this problem, eventually we want to resolve it. For future scrums.
https://discuss.erpnext.com/t/debit-and-credit-not-equal-for-sales-invoice-difference-is/36860/8

**Comment by monroy95** [comment]
Reabrir si la incidencia vuelve a presentarse
