### ISSUE TITLE
Make Return - Credit Note

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/factura_electronica_gt#91]
Comportamiento Actual:
Al momento de hacer click en "Make > Return / Credit Note", se crea un DocType "Sales Invoice" con valores negativos. Sin embargo se elije la serie por omisión, que es la primera en la lista para "Sales Invoice" en "Numbering Series".  El usuario manualmente debe elegir la serie de la nota de crédito. Ocasionalmente causa errores en el flujo el crear una nota de crédito y no cambiar la serie de Factura por omisión por la serie para notas de crédito.

Comportamiento Deseado:
Al momento de crear una nueva Nota de Credito, la aplicación seleccionará la serie por omisión configurada en Configuración de Factura Electrónica, y por lo tanto la colocará en el campo correspondiente, evitándole al usuario tener que seleccionar manualmente la serie de notas de crédito, minimizando la probabilidad de errores y el tiempo invertido en el flujo de trabajo, para incrementar la eficiencia.

**Comment by monroy95** [comment]
Probablemente tenga que ver la configuración de naming series en ERPNext, ya que no pude replicar el problema:

**Funcionando** : Si permite seleccionar la serie

![May-28-2019 17-40-39](https://user-images.githubusercontent.com/26640728/58519221-d4059780-816f-11e9-89e3-4fbcadccab84.gif)

Configuración de naming series (Sales Invoice) en mi server:

![May-28-2019 17-43-12](https://user-images.githubusercontent.com/26640728/58519324-47a7a480-8170-11e9-806f-da634364d543.gif)

**Comment by Tropicalrambler** [comment]
Esto se agreará un campo en config factura electronica para que se indique cual es la nota de credito, nota de debito, quizas factura especial por default.

**Comment by Tropicalrambler** [comment]
No es problema d epoder seleccionar la serie, lo que buscamos es que NO le permita al usuario seleccionar una serie que es para factura, si se esta creando una nota de credito. Si debe forzar la seleccion solamente de series para Notas de Credito.

**Comment by monroy95** [comment]
![return1](https://user-images.githubusercontent.com/26640728/61165286-ad12e300-a4db-11e9-843c-5390f76b4635.gif)

![return2](https://user-images.githubusercontent.com/26640728/61165321-1db9ff80-a4dc-11e9-8a87-06788648b065.gif)

**Comment by monroy95** [comment]
Revisar funcionamiento actual
